apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: production-backend
    environment: production
spec:
  type: ClusterIP
  selector:
    app: production-backend
    environment: production
  ports:
  - name: apache-port
    protocol: TCP
    port: 8080
    targetPort: 8080