apiVersion: v1
kind: Service
metadata:
  name: frontend-external
  labels:
    app: production-frontend
    service-type: external
    environment: production
spec:
  type: NodePort
  selector:
    app: production-frontend
    environment: production
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080