apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: production-frontend
    environment: production
spec:
  type: ClusterIP
  selector:
    app: production-frontend
    environment: production
  ports:
  - name: nginx-port
    protocol: TCP
    port: 80
    targetPort: 80