apiVersion: apps/v1
kind: Deployment
metadata:
  name: production-frontend
  labels:
    app: production-frontend
    environment: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: production-frontend
      environment: production
  template:
    metadata:
      labels:
        app: production-frontend
        environment: production
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        ports:
        - containerPort: 80