apiVersion: apps/v1
kind: Deployment
metadata:
  name: production-backend
  labels:
    app: production-backend
    environment: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: production-backend
      environment: production
  template:
    metadata:
      labels:
        app: production-backend
        environment: production
    spec:
      containers:
        - name: apache
          image: httpd:2.4
          ports:
            - containerPort: 8080
          command: ["/bin/sh", "-c"]
          args:
            - |
              # Копируем стандартную конфигурацию и меняем порт
              cp /usr/local/apache2/conf/httpd.conf /usr/local/apache2/conf/httpd-custom.conf
              sed -i 's/^Listen 80/Listen 8080/g' /usr/local/apache2/conf/httpd-custom.conf
              sed -i 's/^#ServerName www.example.com:80/ServerName localhost:8080/g' /usr/local/apache2/conf/httpd-custom.conf
              # Создаем тестовую страницу
              echo "<h1>Apache Server working on port 8080</h1>" > /usr/local/apache2/htdocs/index.html
              echo "<p>Pod: $(hostname)</p>" >> /usr/local/apache2/htdocs/index.html
              # Запускаем
              httpd -f /usr/local/apache2/conf/httpd-custom.conf -DFOREGROUND
