apiVersion: batch/v1
kind: CronJob
metadata:
  name: data-cleanup
  namespace: user-platform-exam
spec:
  schedule: "{{ .Values.cronSchedules.dataCleanup }}"
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: data-cleanup
              image: "{{ .Values.images.postgres.repository }}:{{ .Values.images.postgres.tag }}"
              env:
                - name: DB_HOST
                  value: "postgres-service.user-platform-exam.svc.cluster.local"
                - name: DB_NAME
                  value: "{{ .Values.postgres.dbName }}"
                - name: DB_USER
                  value: "{{ .Values.postgres.dbUser }}"
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: app-secrets
                      key: db-password
              command: ["/bin/sh","-c"]
              args:
                - |
                  export PGPASSWORD="$DB_PASSWORD"
                  # (30 days/2 minutes для проверки)
                  COUNT=$(psql -h "$DB_HOST" -U "$DB_USER" -d "$DB_NAME" -t -A -v ON_ERROR_STOP=1 -c "WITH d AS (DELETE FROM notifications WHERE created_at < NOW() - INTERVAL '2 minutes' RETURNING 1) SELECT count(*) FROM d;")
                  echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') Deleted notifications older than 30 days: ${COUNT:-0}"
          terminationGracePeriodSeconds: 30