apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: user-platform-exam
type: Opaque
stringData:
  jwt-secret: "{{ .Values.secrets.jwtSecret }}"
  db-password: "{{ .Values.secrets.dbPassword }}"