apiVersion: apps/v1
kind: Deployment
metadata:
  name: slow-start
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slow-start
  template:
    metadata:
      labels:
        app: slow-start
    spec:
      containers:
      - name: app
        image: nginx:alpine
        command: ["/bin/sh", "-c"]
        args:
          - sleep 15 && nginx -g 'daemon off;'
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 2  # Приложение еще не запустится
          periodSeconds: 3