apiVersion: v1
kind: Service
metadata:
  name: web-nodeport 
  labels:
    app: web-app 
    purpose: demonstration 
spec:
  type: NodePort 
  selector:
    app: web-app 
  ports:
    - name: http-web 
      protocol: TCP
      port: 80 
      targetPort: 80 
      nodePort: 30090