apiVersion: v1
kind: Secret
metadata:
  name: name-secret
type: Opaque
data:
  api-key: bXktc3VwZXItYXBpLWtleS0xMjM=
  auth-token: bXktc2VjcmV0LWF1dGgtdG9rZW4tNDU2
  encryption-key: dmVyeS1zZWNyZXQtZW5jcnlwdGlvbi1rZXktNzg5