apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-service-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: multi-service-app
  template:
    metadata:
      labels:
        app: multi-service-app
    spec:
      containers:
        - name: nginx-web
          image: nginx:1.25-alpine
          ports:
            - containerPort: 80
        - name: apache-api
          image: httpd:2.4-alpine
          ports:
            - containerPort: 8080
          command: ["/bin/sh", "-c"]
          args:
            - |
              # Копируем стандартную конфигурацию и меняем порт
              cp /usr/local/apache2/conf/httpd.conf /usr/local/apache2/conf/httpd-custom.conf
              sed -i 's/^Listen 80/Listen 8080/g' /usr/local/apache2/conf/httpd-custom.conf
              sed -i 's/^#ServerName www.example.com:80/ServerName localhost:8080/g' /usr/local/apache2/conf/httpd-custom.conf
              # Создаем тестовую страницу
              echo "<h1>Apache Server working on port 8080</h1>" > /usr/local/apache2/htdocs/index.html
              echo "<p>Pod: $(hostname)</p>" >> /usr/local/apache2/htdocs/index.html
              # Запускаем
              httpd -f /usr/local/apache2/conf/httpd-custom.conf -DFOREGROUND
