apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: multi-service-app
    service: frontend
spec:
  type: ClusterIP
  selector:
    app: multi-service-app
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: multi-service-app
    service: backend
spec:
  type: ClusterIP
  selector:
    app: multi-service-app
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP