# PostgreSQL StatefulSet 
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: user-platform-exam
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: POSTGRES_DB
          value: "userdb"
        - name: POSTGRES_USER
          value: "admin"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: db-password
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata 
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        # PostgreSQL автоматически выполнит скрипты из этой директории
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d
        livenessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command: ["pg_isready", "-U", "admin"]
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: init-script
        configMap:
          name: postgres-init-script
          items:
          - key: init.sql
            path: init.sql
  # VolumeClaimTemplate - хранилище привязано к конкретному Pod
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi 
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: user-platform-exam
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432