apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    app: nginx-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.25
        ports:
        - containerPort: 80
        env:
        - name: nginx-port
          value: "80"
