apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    service-type: internal
spec:
  type: ClusterIP
  selector:
    app: web-app
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
