apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: user-platform-exam
  labels:
    app: user-platform
    component: webapp
spec:
  type: NodePort
  selector:
    app: user-platform
    component: webapp
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30100