apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: user-platform-exam
  labels:
    app: user-platform
    component: config
data:
  SECRET_KEY: "exam-secret-key-2024"
  DATABASE_URL: "postgresql://user:password@db-service/userdb"