apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: user-platform-exam
  labels:
    app: user-platform
    component: database
spec:
  type: ClusterIP
  selector:
    app: user-platform
    component: database
  ports:
  - port: 5432
    targetPort: 5432