apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  namespace: test
  labels:
    app: debug
    env: test
spec:
  volumes:
  - name: shared-volume
    emptyDir: {}
  containers:
  - name: nginx-container
    image: nginx:alpine
    ports:
    - containerPort: 80
    volumeMounts:
    - name: shared-volume
      mountPath: /usr/share/nginx/html
  - name: busybox-container
    image: busybox:latest
    command: ["sh", "-c", "while true; do echo $(date) >> /shared/log.txt; sleep 5; done"]
    volumeMounts:
    - name: shared-volume
      mountPath: /shared
