apiVersion: v1
kind: Pod
metadata:
  name: volume-demo
  labels:
    app: volume-demo
spec:
  containers:
  - name: writer
    image: busybox
    command: ["/bin/sh", "-c"]
    args: ["while true; do echo $(date) >> /shared/data.log; sleep 4; done"]
    volumeMounts:
    - name: shared-vol
      mountPath: /shared

  - name: reader
    image: busybox
    command: ["/bin/sh", "-c"]
    args: ["tail -f /shared/data.log"]
    volumeMounts:
    - name: shared-vol
      mountPath: /shared

  volumes:
  - name: shared-vol
    emptyDir: {}
