apiVersion: v1
kind: Pod
metadata:
  name: combined-pod
spec:
  containers:
  - name: test-container
    image: nginx:alpine 
    env:
      - name: DB_HOST
        valueFrom:
          configMapKeyRef:
            name: app-config       
            key: database.host     
            optional: false        
      - name: DB_PASSWORD 
        valueFrom:
          secretKeyRef:
            name: app-secret     
            key: database.password
            optional: false      
  restartPolicy: Never