apiVersion: v1
kind: Pod
metadata:
  name: problem-app
  labels:
    app: problem-app 
spec:
  containers:
  - name: apache-container
    image: httpd:2.4-alpine
    ports:
    - containerPort: 8080 
    command: ["/bin/sh"]
    args:
    - "-c"
    - |
      # Меняем порт Apache с 80 на 8080
      sed -i 's/^Listen 80/Listen 8080/g' /usr/local/apache2/conf/httpd.conf
      # Создаем простую HTML-страницу для проверки
      echo "<h1>Hello from Problem Pod on port 8080!</h1><p>Pod: $(hostname)</p>" > /usr/local/apache2/htdocs/index.html
      # Запускаем Apache
      httpd -D FOREGROUND