apiVersion: v1
kind: Service
metadata:
  name: ghost-service
spec:
  selector:
    app: non-existent # Селектор, которому ничего не соответствует
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80