apiVersion: v2
name: user-platform-exam
description: Helm chart для всего приложения (auth, profile, notification, report, frontend, postgres, cronjobs)
type: application
version: 0.1.0
appVersion: "1.0"